#: import FadeTransition kivy.uix.screenmanager.FadeTransition

ScreenManagement:
	transition: FadeTransition()
	MainScreen:
	AnotherScreen:
	
<MainScreen>
	name: "main"
	Button:
		on_release: app.root.current = "other"
		text: "Scene Switch"
		font_size: 49

<AnotherScreen>
	name: "other"
	
	
	FloatLayout:
		Painter
		Button:
			color: 0,2,0,1
			font_size: 25
			size_hint: 0.3,0.2
			text: "Home"
			on_release: app.root.current = "main"
			pos_hint: {"right":1,"top":1}